SET FOREIGN_KEY_CHECKS=0;
SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";
CREATE DATABASE IF NOT EXISTS `custom_framework` DEFAULT CHARACTER SET utf8;
USE `custom_framework`;

CREATE TABLE IF NOT EXISTS `groups` (
    `id` int(5) NOT NULL AUTO_INCREMENT,
    `title` varchar(50) CHARACTER SET utf8 NOT NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
